sonar.projectKey=Keidan_asus-touchpad-numpad
sonar.organization=keidan
sonar.sources=src
sonar.coverage.exclusions=**/**
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=rust:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.rs